# Generated by Django 6.1.2 on 2026-10-08 16:55

import django.db.models.deletion
import django.utils.timezone
import nazbeen_forex_ai.analysis.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenshotAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=nazbeen_forex_ai.analysis.storage.get_screenshot_upload_path)),
                ('image_path', models.CharField(blank=True, max_length=512)),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('timeframe', models.CharField(blank=True, max_length=10, null=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('structured_output', models.JSONField(default=dict)),
                ('disagreements', models.JSONField(default=list)),
                ('mtf_conflicts', models.JSONField(default=list)),
                ('evidence', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
