# Generated by Django 6.1.2 on 2026-10-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshotanalysis',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
